import Head from "next/head";

export default function Home() {
  return (
    <div className="App">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="heading-primary">Heading 1</h1>
        <h2 className="heading-secondary">Heading 2</h2>
        <br />
        <h3 className="heading-tertiary">Heading 3</h3>
        <p className="">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam neque,
          repudiandae minima adipisci sit quo odio nisi voluptate quibusdam
          molestiae exercitationem illo ad, eveniet doloremque nesciunt quos
          debitis deserunt dolore!
        </p>
      </main>
    </div>
  );
}
